
from dataclasses import dataclass
import typing
import typing_extensions

from flytekit.core.annotation import FlyteAnnotation

from latch.types.metadata import NextflowParameter
from latch.types.file import LatchFile
from latch.types.directory import LatchDir, LatchOutputDir

# Import these into your `__init__.py` file:
#
# from .parameters import generated_parameters

generated_parameters = {
    'input': NextflowParameter(
        type=LatchFile,
        default=None,
        section_title='Input/output options',
        description='Path to comma-separated file containing information about the samples in the experiment.',
    ),
    'tools': NextflowParameter(
        type=typing.Optional[LatchFile],
        default=None,
        section_title=None,
        description='Path to comma-separated file containing information about the tools to be used in the experiment.',
    ),
    'outdir': NextflowParameter(
        type=typing_extensions.Annotated[LatchDir, FlyteAnnotation({'output': True})],
        default=None,
        section_title=None,
        description='The output directory where the results will be saved. You have to use absolute paths to storage on Cloud infrastructure.',
    ),
    'email': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description='Email address for completion summary.',
    ),
    'multiqc_title': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description='MultiQC report title. Printed as page header, used for filename if not otherwise specified.',
    ),
    'skip_stats': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title='Stats options',
        description='Skip all of the statistics computation on the fasta file.',
    ),
    'calc_sim': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description='Calculate the percentage similarity across the sequences in the input files.',
    ),
    'calc_seq_stats': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description='Calculate general statistics on input files.',
    ),
    'extract_plddt': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description='Extract plddt from structure files. Only works if the files have been generated by AF2.',
    ),
    'calc_gaps': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description='Extract total number of gaps and average number of gaps of the alignment.',
    ),
    'skip_eval': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title='Eval options',
        description='Skip all of the evaluations computation on the msa.',
    ),
    'calc_sp': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description='Calculate the Sum of Pairs of alignment.',
    ),
    'calc_tc': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description='Calculate the Total Column Score of alignment.',
    ),
    'calc_irmsd': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description='Calculate the iRMSD of alignment.',
    ),
    'calc_tcs': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description='Calculate the Transitive Consistency Score (TCS) of alignment.',
    ),
    'skip_multiqc': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title='Reports options',
        description='Skip the multiqc report generation.',
    ),
    'skip_shiny': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description='Skip the shiny report generation.',
    ),
    'shiny_app': NextflowParameter(
        type=typing.Optional[LatchDir],
        default=None,
        section_title=None,
        description='File containing the main shiny app.',
    ),
    'shiny_trace_mode': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description='variable containing the shiny_trace mode to be used.',
    ),
    'no_compression': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title='Compression',
        description='Produce uncompressed alignment files',
    ),
    'multiqc_methods_description': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title='Generic options',
        description='Custom MultiQC yaml file containing HTML including a methods description.',
    ),
}

